### ISSUE TITLE
Layout array bug.

### ISSUE THREAD

**Issue by yiwenxue** [plasmoduck/modwm#2]
https://github.com/plasmoduck/modwm/blob/b5a032d698dca18a86fa8f2da96e1fbee312c8b9/config.def.h#L511
There is a memory bug when you enable cyclelayout_patch.
I think you should add
```C
	#if CYCLELAYOUTS_PATCH
	{ NULL,       NULL,             {0} },
	#endif
```
to the end of this array.

**Comment by plasmoduck** [comment]
Fixed in https://github.com/plasmoduck/modwm/commit/c800cf34ba8eacf1ae6f8c9324106f1a3a24eddd hope this helps :)
