### ISSUE TITLE
Error in make file

### ISSUE THREAD

**Issue by m-althaf** [plasmoduck/modwm#3]
![pic-full-201227-1022-08](https://user-images.githubusercontent.com/41832211/103164152-80689d80-482d-11eb-8cf1-2c34571ca8d1.png)

couldn't understand what went wrong

**Comment by plasmoduck** [comment]
Are you using Linux? If so try removing the . Dots I front of the .if .else etc statements. FreeBSD requires them.

**Comment by m-althaf** [comment]
Yes, it works!!
thanks
