### ISSUE TITLE
Very slow switching workspaces

### ISSUE THREAD

**Issue by ghost** [plasmoduck/modwm#4]
Hi,

Would love to use this, but even with the default patch set switching workspaces is taking a good solid second on a 4 core ryzen and a Samsung evo ssd. Not sure what is going on here. Doesn't happen on stock dwm, or my currently daily driver bspwm.

Using FreeBSD-12.2-RELEASE-p2 and modwm commit  b76057a36ca0df267f00e37168289f967a749e55.

Can you give me any debugging advise?

Thank you!

**Comment by plasmoduck** [comment]
You mean when you switch tags (MOD+1 MOD+2) etc? Strange, I havent heard of that before. I'm running the same FreeBSD version.

**Comment by ghost** [comment]
Yeah I tried disabling a bunch of patch sets that were defaults that I thought could cause an issue but it persists. Stock dwm has never been an issue.

**Comment by ghost** [comment]
OK, I have been playing with some stuff and tracked it down to a single patch. It seems when the DEFAULT_TAGS are on its laggy for me, maybe a font issue? When I switch to the ALTERNATIVE_TAGS 1,2,3,4,etc it's speedy as I would expect.

**Comment by plasmoduck** [comment]
Yes it's trying to draw the glyphs for the font 'siji' which you don't have installed since the DEFAULT_TAGS is set to use siji glyphs.

**Comment by plasmoduck** [comment]
I have made quite a few changes including setting DEFAULT_TAGS to a more sane 1, 2, 3, etc. So a git pull might be worthwhile.

**Comment by ghost** [comment]
Working well, thanks for the help.
