### ISSUE TITLE
It look so great. How can I contribute to it？

### ISSUE THREAD

**Issue by HIDE-r** [plasmoduck/modwm#5]
I have been using it for a while. I think it so awesome, it help me reduce the time to modify dwm a lot. 
by the way, in README, the picture show weechat is awesome too, how can I config it same to you?

**Comment by plasmoduck** [comment]
Yes that is the aim of this project. To provide a good looking usable dwm experience out-of-the-box.

In the screenshot I am using st terminal with the same gruvbox colorscheme as modwm so all the colors match. You can configure weechat using /fset and install scripts with /script

As for contributing, what did you have in mind?

**Comment by HIDE-r** [comment]
Thanks~ I will try to configure the weechat later. 
for my mind?... emm... To be honest, I don't know. But when I use this project in my Arch Linux, I changed some configuration  that make it to work, I think it can be modified to make newer user more easier to use.
I'm a young coder, maybe I can't help you much.  Are there any groups that allow me to join the discussion? The people around me both don’t play these things, But I am very interested in DWM, suckless utils, and more about *nix. hhhh
My English is week, Dont't laugh at me~     XD

**Comment by plasmoduck** [comment]
This build is mostly for my personal use as I use FreeBSD as stated in the readme. But it started to gain a lot of attention so I made it public. It is fairly easy to modify the header files to suit you OS. As for best place for discussion is probably irc.freenode.org #suckless

**Comment by HIDE-r** [comment]
OK. thank for you.
