### ISSUE TITLE
Cause keybind issue when uninstall and re-install orignal dwm

### ISSUE THREAD

**Issue by shoraaa** [plasmoduck/modwm#6]
Install modwm with root seem to make the keybind break when switch back to dwm. Mouse still work. Tried _sudo make clean uninstall_

**Comment by plasmoduck** [comment]
I'm not sure what you mean. Do you installed modwm with 'sudo make install" then decided to go back to vanila dwm and done 'sudo make uninstall'. Then you reinstalled vanilla dwm 'cd dwm && sudo make install' but the dwm keybinds dont work? I dont think thats anything to do with modwm. Just make sure you are using the actual dwm config.def.h/config.h and not the modwm one.

**Comment by plasmoduck** [comment]
Have you fixed this issue? If so do you mind closing it? If not, let me know if you need more help.

Cheers 😀

**Comment by shoraaa** [comment]
> Have you fixed this issue? If so do you mind closing it? If not, let me know if you need more help.
> 
> Cheers 😀

I still havent fixed it, since re-complie the orignal dwm make the keyboard do nothing, so i am now only using the modwm itself. Because of not having a single clue of this happen, maybe i will just re-install arch linux if needed, closing this :)
