### ISSUE TITLE
How can I zoom statusbar icon?

### ISSUE THREAD

**Issue by HIDE-r** [plasmoduck/modwm#7]
![image](https://user-images.githubusercontent.com/51672711/109110301-d2686980-7771-11eb-8293-7e515a094355.png)
in the left hand side of the statusbar, as you see that. It is small icon. how can I enlarge the icon like you? 
Another question, in my vim, the icon will show incorrect. Do you know how can you show it correct? in my terminal, if I set Siji only for my terminal font,  although it can show correct, terminal will be very ugly. This is not what i want.
![image](https://user-images.githubusercontent.com/51672711/109110819-c9c46300-7772-11eb-9503-b22a1be83e31.png)

**Comment by plasmoduck** [comment]
Hi, for glyphs appearing correctly in terminal, try setting something like this in your st/config.h

` static char *font = {
        "JetBrains Mono:pixelsize=18:antialias=true:autohint=true",
        "siji:pixelsize=10:antialias=true:autohint=true"
 };`

As for the size of the glyphs in the statusbar make sure you have this;

`static const char *fonts[]               = { "siji:pixelsize=22", "JetBrains Mono:pixelsize=20" };`

Also, I use the [ttf version of siji](https://github.com/fauno/siji/blob/master/ttf/siji.ttf) not the bitmap version in the repos.

Oh and BTW, I have made some big changes to statusbar.sh if you want to check it out.

Good luck 😀

**Comment by HIDE-r** [comment]
Great! The icon is now ready to display its normal size. I might have used the bitmap version before, so I can't enlarge the icon font.
In my st, I add the font2 patch to support multiple fonts. I also show the glyphs correctly now. Your way maybe have something wrong?
I just pull your latest code. I will continue to try it. XD 
Thank for your help~

**Comment by plasmoduck** [comment]
Glad to see you sorted it out 😃
