### ISSUE TITLE
bar border patch doesnt work!

### ISSUE THREAD

**Issue by siduck** [plasmoduck/modwm#8]
Hi there , nice dwm build . Im trying to patch the bar border patch but it erases some stuff in my dwmbar .

My dwmbar has following patches : notitle , systray , status2d and barheight.

after adding bar border patch , the dwm bar looks weird :/

before : 
![image](https://user-images.githubusercontent.com/59060246/126347549-c0415c00-2be0-4b21-940b-b395dcc823ce.png)

after :
![image](https://user-images.githubusercontent.com/59060246/126347598-bdecd688-241f-42ca-b8da-1121c3fb2093.png)

**Comment by plasmoduck** [comment]
Are you trying to take the patch from my build and add it to your own?
If so, then this is the original [patch](https://codemadness.org/paste/dwm-border-bar.patch)

**Comment by siduck** [comment]
> Are you trying to take the patch from my build and add it to your own?
> If so, then this is the original [patch](https://codemadness.org/paste/dwm-border-bar.patch)

yes Im using the original patch

**Comment by siduck** [comment]
where do I get your patch?

**Comment by siduck** [comment]
nvm this guy helped a lot and modified the patch for my build! https://www.reddit.com/r/suckless/comments/on80gv/dwm_statuspadding_patch_conflicts_with_status2d/h5wg6pz?utm_source=share&utm_medium=web2x&context=3
