### ISSUE TITLE
alpha patch module error

### ISSUE THREAD

**Issue by ddiaz2380** [plasmoduck/modwm#9]
When I change the value I have this error, if I leave it at 0 it compiles perfect ...

`136 warnings generated.
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/local/include -I/usr/local/include/freetype2   -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\"  util.c
cc -o dwm drw.o dwm.o util.o -L/usr/local/lib -lX11  -lfontconfig -lXft
ld: error: undefined symbol: XRenderFindVisualFormat
>>> referenced by dwm.c
>>>               dwm.o:(main)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1
`

P/D: It doesn't show me the icons ... should I add something else? any font?

**Comment by plasmoduck** [comment]
Did you edit config.mk and uncomment #XRENDER = -lXrender
Also for the icons, you need [this](https://github.com/fauno/siji/blob/master/ttf/siji.ttf) font.

**Comment by ddiaz2380** [comment]
thx!

**Comment by ddiaz2380** [comment]
thx!

**Comment by plasmoduck** [comment]
No worries, all working? Could you link a screenshot of your setup?

**Comment by ddiaz2380** [comment]
I am installing in the ssd I was testing it virtual, I really like bsd because of the data handling in zsf and other things, its dwm configuration is excellent I tried it a bit and I love it!
As soon as I finished configuring a bit, all I upload images of how I look. I hope I don't have issues with the nvidia drivers that always give me trouble.

**Comment by plasmoduck** [comment]
Are you using FreeBSD? If so you can just install the lastest nvidia driver from pkg

**Comment by ddiaz2380** [comment]
Hi! I take the nvidia driver and configure them in both the /boot/loader.conf and /etc/rc.conf but it still takes a maximum of 1024x768 in the xrandr.
Nor can I compile st and dmenu even though I change the path. I have void linux on my main pc with all my configuration that I use, as I mentioned I wanted to switch to freebds but until I have time to solve all this I will apparently take a few more days. Is it possible to lift your modwm configuration in void linux?
Greetings!

https://ibb.co/SJ4QXtd
https://ibb.co/hysLr86

**Comment by plasmoduck** [comment]
Nice, for st, you need to uncomment the #OpenBSD xfont section in config.mk. Or you could just use my FreeBSD patched st, dmenu, surf etc [here](https://github.com/plasmoduck/suckless)

For nvidia on FreeBSD install nvidia-xconfig-460.73.01 nvidia-driver-460.84 and nvidia-driver-460.84 then run nvidia-xconfig and startx then you can use nvidia-settings to change your resolution

**Comment by plasmoduck** [comment]
Hi, looks like you are missing pkg-config. Try 'pkg install pkg-config'. Then try again, delete config.h first then try to make install.
